# Generated by Django 3.0.6 on 2020-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='img_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
